### ISSUE TITLE
Update Bootstrap

### ISSUE THREAD

**Issue by jdorfman** [Mandihamza/neil-degrasse-tyson-tribute-page#1]
Remove the current version of Bootstrap with an updated version using [BootstrapCDN](https://www.bootstrapcdn.com) 

Line in question:
https://github.com/Mandihamza/neil-degrasse-tyson-tribute-page/blob/2c5bd7434de748985fd54fda3f5f32b110854090/index.html#L6

**Comment by Mandihamza** [comment]
Updated!

**Comment by Mandihamza** [comment]
Updated to include integrity and crossorigin attributes.
